app:
  name: dreamteam
  env: development
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  name: sandeepsecurities

jwt:
  SecretKey: secret
  expiration: 1h

profiling:
  enabled: true
  port: 6060